name: CI
on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run lint
        run: deno lint

      - name: Run tests
        run: deno test

      - name: Build
        run: # TODO: Add build steps
